#!/usr/bin/env python3
"""
C64 Stream - Preset-based E2E Test Runner
Copyright (C) 2025 Christian Gleissner

Licensed under the GNU General Public License v2.0 or later.
See <https://www.gnu.org/licenses/> for details.

This script runs E2E tests for specific effect presets, managing:
- Generation of preset-specific properties.ini files
- Organization of results into per-preset folders
- Running the assertion framework against recorded output
"""

import argparse
import configparser
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

# Paths
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
PRESETS_INI = PROJECT_ROOT / "data" / "effect_presets.ini"
BASE_PROPERTIES_LOCAL = SCRIPT_DIR / "properties_e2e_local.ini"
BASE_PROPERTIES_CI = SCRIPT_DIR / "properties_e2e_ci.ini"
RESULTS_DIR = SCRIPT_DIR / "results"


def load_preset_settings(preset_name: str) -> Optional[dict[str, str]]:
    """Load effect settings from effect_presets.ini for a given preset."""
    if not PRESETS_INI.exists():
        print(f"❌ Presets file not found: {PRESETS_INI}")
        return None

    parser = configparser.ConfigParser()
    parser.read(PRESETS_INI)

    # Normalize preset name for section lookup
    normalized = preset_name.lower().replace("_", " ")

    for section in parser.sections():
        if section.lower() == normalized:
            return dict(parser.items(section))

    # Try with underscores
    normalized = preset_name.lower().replace(" ", "_")
    for section in parser.sections():
        if section.lower().replace(" ", "_") == normalized:
            return dict(parser.items(section))

    print(f"❌ Preset not found: {preset_name}")
    print(f"Available presets: {', '.join(parser.sections())}")
    return None


def generate_preset_properties(preset_name: str, settings: dict[str, str], is_ci: bool = False) -> Path:
    """Generate a properties.ini file with the preset's effect settings."""
    # Start with base E2E properties
    base_file = BASE_PROPERTIES_CI if is_ci else BASE_PROPERTIES_LOCAL
    if not base_file.exists():
        raise FileNotFoundError(f"Base properties file not found: {base_file}")

    parser = configparser.ConfigParser()
    parser.read(base_file)

    # Ensure [effects] section exists
    if "effects" not in parser.sections():
        parser.add_section("effects")

    # Apply preset effect settings
    for key, value in settings.items():
        parser.set("effects", key, value)

    # Write to temporary file
    output_name = preset_name.lower().replace(" ", "_")
    output_file = SCRIPT_DIR / f"properties_e2e_{output_name}.ini"

    with open(output_file, "w") as f:
        f.write(f"# C64 Stream E2E Properties - {preset_name} preset\n")
        f.write("# Auto-generated by preset_runner.py\n#\n")
        parser.write(f)

    return output_file


def setup_preset_scenario(preset_name: str, properties_file: Path) -> Path:
    """
    Create a scenario overrides directory for the preset.

    This creates the directory structure that e2e.py's apply_scenario_overrides()
    expects, mirroring ~/.config/obs-studio.
    """
    scenario_dir = SCRIPT_DIR / "scenarios" / "presets" / preset_name.lower().replace(" ", "_")
    plugin_dir = scenario_dir / "plugins" / "c64stream" / "data"

    # Clean and recreate
    if scenario_dir.exists():
        shutil.rmtree(scenario_dir)
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Copy the preset properties file
    shutil.copy2(properties_file, plugin_dir / "properties.ini")

    return scenario_dir


def get_results_dir(preset_name: str, format_name: str) -> Path:
    """Get the results directory for a preset and format combination."""
    preset_key = preset_name.lower().replace(" ", "_")
    return RESULTS_DIR / format_name.lower() / preset_key


def run_e2e_for_preset(
    preset_name: str,
    format_name: str = "PAL",
    frames: int = 180,
    verbose: bool = False,
    is_ci: bool = False,
    skip_assertions: bool = False,
) -> tuple[bool, dict]:
    """
    Run E2E test for a specific preset.

    Returns:
        Tuple of (success: bool, results: dict)
    """
    print(f"\n{'='*60}")
    print(f"E2E Test: {preset_name} ({format_name})")
    print(f"{'='*60}\n")

    # Load preset settings
    settings = load_preset_settings(preset_name)
    if not settings:
        return False, {"error": f"Failed to load preset: {preset_name}"}

    # Generate preset-specific properties
    print(f"📝 Generating properties for preset: {preset_name}")
    properties_file = generate_preset_properties(preset_name, settings, is_ci)
    print(f"   Generated: {properties_file}")

    # Setup scenario overrides directory
    print(f"📁 Setting up scenario overrides")
    scenario_dir = setup_preset_scenario(preset_name, properties_file)
    print(f"   Scenario dir: {scenario_dir}")

    # Prepare output directory
    output_dir = get_results_dir(preset_name, format_name)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"   Output dir: {output_dir}")

    # Build the e2e.sh command
    e2e_script = SCRIPT_DIR / "e2e.sh"

    cmd = [
        str(e2e_script),
        "--format", format_name,
        "--frames", str(frames),
        "--output-dir", str(output_dir),
        "--scenario-overrides", str(scenario_dir),
    ]

    if verbose:
        cmd.append("--verbose")

    if is_ci:
        # In CI, skip build if plugin is already installed
        cmd.append("--skip-build")

    # Run E2E test
    print(f"\n🧪 Running E2E test...")
    if verbose:
        print(f"   Command: {' '.join(cmd)}")

    try:
        result = subprocess.run(
            cmd,
            cwd=str(SCRIPT_DIR),
            capture_output=not verbose,  # Show output if verbose
            text=True,
        )
        e2e_success = result.returncode == 0

        if not e2e_success and not verbose:
            print(f"❌ E2E test failed:")
            print(result.stdout[-2000:] if len(result.stdout) > 2000 else result.stdout)
            print(result.stderr[-1000:] if len(result.stderr) > 1000 else result.stderr)

    except Exception as e:
        print(f"❌ E2E test exception: {e}")
        return False, {"error": str(e)}

    # Find the recording
    recording = None
    for ext in [".mp4", ".mkv"]:
        candidates = list(output_dir.glob(f"*{ext}"))
        if candidates:
            recording = candidates[0]
            break

    results = {
        "preset": preset_name,
        "format": format_name,
        "e2e_passed": e2e_success,
        "recording": str(recording) if recording else None,
        "output_dir": str(output_dir),
    }

    # Run assertions if E2E passed and we have a recording
    if not skip_assertions and e2e_success and recording:
        print(f"\n🔍 Running assertions...")
        assertion_results = run_assertions(recording, preset_name, properties_file, verbose)
        results["assertions"] = assertion_results
        results["all_passed"] = assertion_results.get("all_passed", False)
    else:
        results["all_passed"] = e2e_success

    return results["all_passed"], results


def run_assertions(
    recording: Path,
    preset_name: str,
    properties_file: Path,
    verbose: bool = False,
) -> dict:
    """Run the assertion framework against a recording."""
    assertion_script = SCRIPT_DIR / "assertion_framework.py"

    cmd = [
        sys.executable,
        str(assertion_script),
        "--mp4", str(recording),
        "--preset", preset_name.lower().replace(" ", "_"),
        "--properties", str(properties_file),
        "--json",
    ]

    if verbose:
        cmd.append("--verbose")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(SCRIPT_DIR))

        # Try to parse JSON output
        try:
            assertion_data = json.loads(result.stdout)
            assertion_data["all_passed"] = assertion_data.get("failed", 1) == 0
            return assertion_data
        except json.JSONDecodeError:
            return {
                "all_passed": result.returncode == 0,
                "raw_output": result.stdout,
                "error": result.stderr if result.returncode != 0 else None,
            }

    except Exception as e:
        return {"all_passed": False, "error": str(e)}


def list_presets() -> list[str]:
    """List all available presets."""
    if not PRESETS_INI.exists():
        return []

    parser = configparser.ConfigParser()
    parser.read(PRESETS_INI)
    return parser.sections()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run E2E tests for specific effect presets",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Test single preset
  %(prog)s --preset arcade_cabinet

  # Test all presets
  %(prog)s --all-presets

  # Test with NTSC format
  %(prog)s --preset green_monitor --format NTSC

  # List available presets
  %(prog)s --list-presets
""",
    )

    parser.add_argument("--preset", help="Effect preset name to test")
    parser.add_argument("--all-presets", action="store_true", help="Test all presets")
    parser.add_argument("--format", choices=["PAL", "NTSC"], default="PAL", help="Video format")
    parser.add_argument("--frames", type=int, default=180, help="Number of frames (default: 180 = 3.6s PAL)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Enable verbose output")
    parser.add_argument("--ci", action="store_true", help="CI mode (use CI properties, skip build)")
    parser.add_argument("--skip-assertions", action="store_true", help="Skip assertion verification")
    parser.add_argument("--list-presets", action="store_true", help="List available presets")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")

    args = parser.parse_args()

    # List presets mode
    if args.list_presets:
        presets = list_presets()
        if args.json:
            print(json.dumps({"presets": presets}))
        else:
            print("Available presets:")
            for p in presets:
                print(f"  - {p}")
        return 0

    # Determine which presets to test
    if args.all_presets:
        presets_to_test = list_presets()
    elif args.preset:
        presets_to_test = [args.preset]
    else:
        parser.error("Must specify --preset or --all-presets")

    # Run tests
    all_results = {}
    all_passed = True

    for preset in presets_to_test:
        passed, results = run_e2e_for_preset(
            preset_name=preset,
            format_name=args.format,
            frames=args.frames,
            verbose=args.verbose,
            is_ci=args.ci,
            skip_assertions=args.skip_assertions,
        )
        all_results[preset] = results
        if not passed:
            all_passed = False

    # Output summary
    if args.json:
        print(json.dumps({"all_passed": all_passed, "results": all_results}, indent=2))
    else:
        print(f"\n{'='*60}")
        print("Summary")
        print(f"{'='*60}")
        for preset, results in all_results.items():
            status = "✅" if results.get("all_passed") else "❌"
            print(f"  {status} {preset}")
        print(f"{'='*60}")
        print(f"Overall: {'✅ All passed' if all_passed else '❌ Some tests failed'}")

    return 0 if all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
