from __future__ import annotations
import glob
import time
import random
import threading
import subprocess
import logging
from pathlib import Path
from typing import Optional, Dict, List, Any, Tuple

from ..environment import Environment

logger = logging.getLogger(__name__)

class PacketReplayer:
    """Handles generation of packet timeline and execution of C binary replayer."""

    def __init__(self, env: Environment, video_format: str = 'PAL', network_simulation: Optional[Dict] = None):
        self.env = env
        self.format = video_format
        self.network_simulation = network_simulation or {}
        self.simulation_stats = {
            'dropped_video': 0, 'dropped_audio': 0,
            'duplicated_video': 0, 'duplicated_audio': 0,
        }

    def replay(self,
               udp_replay_bin: Path,
               video_dest: Tuple[str, int],
               audio_dest: Tuple[str, int]) -> bool:
        """Replay packets to destination."""

        video_dir = (self.env.packet_dir / 'video' / self.format).resolve()

        # Optional replacement audio packet set (e.g. 'sine1k' for click-detection
        # scenarios). Generated by shell_lib/packets.sh into audio_<set>/<FORMAT>.
        audio_set = str(self.network_simulation.get('audio_packet_set', '') or '').strip()
        if audio_set:
            audio_dir = (self.env.packet_dir / f'audio_{audio_set}' / self.format).resolve()
        else:
            audio_dir = (self.env.packet_dir / 'audio' / self.format).resolve()

        if not video_dir.exists() or not audio_dir.exists():
            raise FileNotFoundError(f"Packet directories not found: {video_dir}, {audio_dir}")

        # Load packet files
        video_files = sorted(glob.glob(str(video_dir / "*.bin")))
        audio_files = sorted(glob.glob(str(audio_dir / "*.bin")))

        if not video_files or not audio_files:
            logger.error("❌ No packet files found")
            return False

        logger.info(f"📦 Loaded {len(video_files)} video packets, {len(audio_files)} audio packets")

        # 1. Calculate intervals
        if self.format == 'PAL':
            video_interval_us = 293.384
            audio_interval_us = 4001.417
        else:  # NTSC
            video_interval_us = 278.586
            audio_interval_us = 4005.006

        # 2. Build Timeline
        timeline = []
        start_time_us = 0

        # Add video packets to timeline
        for i, video_file in enumerate(video_files):
            timeline.append({
                'time_us': start_time_us + i * video_interval_us,
                'type': 'video',
                'file': video_file,
                'dest': video_dest
            })

        # Add audio packets to timeline
        for i, audio_file in enumerate(audio_files):
            timeline.append({
                'time_us': start_time_us + i * audio_interval_us,
                'type': 'audio',
                'file': audio_file,
                'dest': audio_dest
            })

        timeline.sort(key=lambda x: x['time_us'])

        # 3. Apply Simulation
        self._apply_simulation(timeline)

        # 4. Generate Manifests
        logger.info(f"🎯 Generated {len(timeline)} interleaved packets over {timeline[-1]['time_us']/1000:.1f}ms")

        video_manifest = [e for e in timeline if e['type'] == 'video']
        audio_manifest = [e for e in timeline if e['type'] == 'audio']

        video_manifest_path = self.env.output_dir / 'video_manifest.csv'
        audio_manifest_path = self.env.output_dir / 'audio_manifest.csv'

        self._write_manifest(video_manifest_path, video_manifest)
        self._write_manifest(audio_manifest_path, audio_manifest)

        # 5. Execute Replay
        if not udp_replay_bin.exists():
            raise FileNotFoundError(f"udp_replay not found: {udp_replay_bin}")

        # Synchronize start time across both senders to avoid A/V offset.
        # Use a future monotonic timestamp so both processes can preload packets
        # and start sending at the exact same time (critical for A/V sync).
        # Lead time: 8-10 seconds to handle slow disk I/O (especially on CI).
        lead_s = 10.0 if self.env.is_ci else 8.0
        start_at_us = (time.monotonic_ns() // 1000) + int(lead_s * 1_000_000)

        # Command construction
        # udp-replay --host <ip> --port <port> --manifest <csv> --dir <dir> --start-at-us <us>

        video_cmd = [
            '--host', video_dest[0],
            '--port', str(video_dest[1]),
            '--manifest', str(video_manifest_path),
            '--dir', str(video_dir),
            '--start-at-us', str(start_at_us),
            '--verbose'
        ]

        audio_cmd = [
            '--host', audio_dest[0],
            '--port', str(audio_dest[1]),
            '--manifest', str(audio_manifest_path),
            '--dir', str(audio_dir),
            '--start-at-us', str(start_at_us),
            '--verbose'
        ]

        logger.info(f"🚀 Synchronized packet replay start: +{lead_s}s from now")
        return self._execute_parallel_replay(udp_replay_bin, video_cmd, audio_cmd)

    # Keys that activate the loss/duplication simulation extensions. When none of
    # these are present the simulation behaves exactly as before (jitter/reorder
    # with an unseeded RNG), keeping all pre-existing scenarios untouched.
    _EXTENDED_SIM_KEYS = (
        'loss_percent', 'audio_loss_percent', 'video_loss_percent',
        'duplicate_percent', 'burst_loss_ms', 'seed',
    )

    def _apply_simulation(self, timeline: List[Dict]):
        """Apply loss, duplication, burst outages, jitter, and reordering.

        Dropped events are removed from the timeline BEFORE manifests are
        written, and duplicated events appear twice, so the manifest files
        remain the exact ground truth of what was sent.
        """
        sim = self.network_simulation
        deterministic = any(sim.get(k) is not None for k in self._EXTENDED_SIM_KEYS)
        if deterministic:
            seed = int(sim.get('seed', 64) or 64)
            rng = random.Random(seed)
            logger.info(f"🎲 Deterministic network simulation (seed={seed})")
        else:
            rng = random.Random()  # legacy behavior: unseeded

        self.simulation_stats = {
            'dropped_video': 0, 'dropped_audio': 0,
            'duplicated_video': 0, 'duplicated_audio': 0,
        }

        # 1. Random per-packet loss (uniform or per-stream).
        loss_percent = float(sim.get('loss_percent', 0) or 0)
        audio_loss_percent = float(sim.get('audio_loss_percent', loss_percent) or 0)
        video_loss_percent = float(sim.get('video_loss_percent', loss_percent) or 0)

        if audio_loss_percent > 0 or video_loss_percent > 0:
            kept = []
            for event in timeline:
                p = audio_loss_percent if event['type'] == 'audio' else video_loss_percent
                if p > 0 and rng.uniform(0, 100) < p:
                    self.simulation_stats[f"dropped_{event['type']}"] += 1
                else:
                    kept.append(event)
            timeline[:] = kept

        # 2. Periodic burst outages (drop everything in the window).
        burst_loss_ms = float(sim.get('burst_loss_ms', 0) or 0)
        burst_loss_interval_ms = float(sim.get('burst_loss_interval_ms', 0) or 0)
        burst_loss_stream = str(sim.get('burst_loss_stream', 'both') or 'both').strip().lower()

        if burst_loss_ms > 0 and burst_loss_interval_ms > 0:
            burst_us = burst_loss_ms * 1000.0
            interval_us = burst_loss_interval_ms * 1000.0
            kept = []
            for event in timeline:
                # First outage begins one full interval in, so stream startup
                # (format detection, first frame) is never inside a burst.
                since_start = event['time_us'] - interval_us
                in_burst = since_start >= 0 and (since_start % interval_us) < burst_us
                matches = burst_loss_stream in ('both', event['type'])
                if in_burst and matches:
                    self.simulation_stats[f"dropped_{event['type']}"] += 1
                else:
                    kept.append(event)
            timeline[:] = kept

        dropped_a = self.simulation_stats['dropped_audio']
        dropped_v = self.simulation_stats['dropped_video']
        if dropped_a or dropped_v:
            logger.info(f"📉 Loss: dropped {dropped_a} audio / {dropped_v} video packets")

        # 3. Duplication: the duplicate is re-sent 0..duplicate_max_delay_ms later.
        duplicate_percent = float(sim.get('duplicate_percent', 0) or 0)
        duplicate_max_delay_ms = float(sim.get('duplicate_max_delay_ms', 40) or 40)

        if duplicate_percent > 0:
            duplicates = []
            for event in timeline:
                if rng.uniform(0, 100) < duplicate_percent:
                    dup = dict(event)
                    dup['time_us'] = event['time_us'] + rng.uniform(0, duplicate_max_delay_ms * 1000.0)
                    duplicates.append(dup)
                    self.simulation_stats[f"duplicated_{event['type']}"] += 1
            timeline.extend(duplicates)
            logger.info(f"📄 Duplication: {self.simulation_stats['duplicated_audio']} audio / "
                        f"{self.simulation_stats['duplicated_video']} video packets duplicated "
                        f"(0-{duplicate_max_delay_ms}ms re-send delay)")

        jitter_percent = sim.get('jitter_percent', 0)
        max_jitter_ms = sim.get('max_jitter_ms', 0)

        if max_jitter_ms > 0:
            jitter_count = 0
            max_jitter_us = max_jitter_ms * 1000
            for i in range(1, len(timeline)):
                jitter = rng.uniform(0, max_jitter_us)
                timeline[i]['time_us'] += jitter
                jitter_count += 1
            logger.info(f"📊 Jitter enabled: 0-{max_jitter_ms}ms positive delay applied to {jitter_count} packets")

        elif jitter_percent > 0:
            jitter_count = 0
            for i in range(1, len(timeline)):
                prev_time = timeline[i-1]['time_us']
                current_time = timeline[i]['time_us']
                base_interval = current_time - prev_time
                jitter_range = base_interval * jitter_percent / 100.0
                jitter = rng.uniform(0, jitter_range)
                timeline[i]['time_us'] += jitter
                jitter_count += 1
            logger.info(f"📊 Jitter enabled: 0-{jitter_percent}% positive delay applied to {jitter_count} packet intervals")

        reorder_percent = sim.get('reorder_percent', 0)
        reorder_max_delay_ms = sim.get('reorder_max_delay_ms', 0)

        if reorder_percent > 0 and reorder_max_delay_ms > 0:
            reorder_count = 0
            for event in timeline:
                if rng.randint(0, 99) < reorder_percent:
                    delay_us = rng.randint(0, reorder_max_delay_ms * 1000)
                    event['time_us'] += delay_us
                    reorder_count += 1
            logger.info(f"🔀 Packet reordering enabled: {reorder_percent}% probability, 0-{reorder_max_delay_ms}ms buffer")

        timeline.sort(key=lambda x: x['time_us'])

    def _write_manifest(self, path: Path, events: List[Dict]):
        """Write manifest CSV."""
        MIN_PACKET_DELAY_US = 50 if self.env.is_ci else 1

        with open(path, 'w') as f:
            f.write("filename,delay_us\n")
            last_sent_time_us = 0

            for event in events:
                event_time_us = int(round(float(event['time_us'])))
                delta_us = event_time_us - last_sent_time_us
                if delta_us < MIN_PACKET_DELAY_US:
                    delta_us = MIN_PACKET_DELAY_US
                filename = Path(event['file']).name
                f.write(f"{filename},{int(delta_us)}\n")
                last_sent_time_us += int(delta_us)

    def _execute_parallel_replay(self, bin_path: Path, video_cmd: List[str], audio_cmd: List[str]) -> bool:
        """Execute video and audio replay in parallel."""
        replay_start_time = time.time()

        video_result = {'rc': None, 'lines': []}
        audio_result = {'rc': None, 'lines': []}

        def run_sender(args, label, result_dict):
            full_cmd = [str(bin_path)] + args
            try:
                proc = subprocess.Popen(
                    full_cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    bufsize=1
                )
                lines = []
                for line in proc.stdout:
                    line = line.rstrip('\n')
                    if line:
                        if len(lines) < 200:
                            lines.append(line)
                        logger.info(f"[{label}] {line}")

                result_dict['rc'] = proc.wait()
                result_dict['lines'] = lines
            except Exception as e:
                result_dict['rc'] = -1
                result_dict['lines'] = [str(e)]

        t1 = threading.Thread(target=run_sender, args=(video_cmd, 'UDP-VIDEO', video_result))
        t2 = threading.Thread(target=run_sender, args=(audio_cmd, 'UDP-AUDIO', audio_result))

        t1.start()
        t2.start()
        t1.join()
        t2.join()

        elapsed_ms = (time.time() - replay_start_time) * 1000

        success = True
        if video_result['rc'] != 0:
            logger.error("❌ Video sender failed")
            for l in video_result['lines'][-10:]: logger.error(f"[UDP-VIDEO] {l}")
            success = False

        if audio_result['rc'] != 0:
            logger.error("❌ Audio sender failed")
            for l in audio_result['lines'][-10:]: logger.error(f"[UDP-AUDIO] {l}")
            success = False

        if success:
            logger.info(f"✅ Packet replay complete in {elapsed_ms:.1f}ms")

        return success
