name: Dispatch
run-name: Dispatched Repository Actions - ${{ inputs.job }} ⌛️
on:
  workflow_dispatch:
    inputs:
      job:
        description: Dispatch job to run
        required: true
        type: choice
        options:
          - build
permissions:
  contents: write
jobs:
  check-and-build:
    if: inputs.job == 'build'
    name: Build Project 🧱
    uses: ./.github/workflows/build-project-flexible.yaml
    with:
      use_containerized: true
      use_containerized_e2e: true
    secrets: inherit
    permissions:
      contents: read
      packages: read
      actions: write
